const students=[{
    "id": 1,
    "first_name": "Stacia",
    "last_name": "Hickinbottom",
    "email": "shickinbottom0@cbc.ca"
  }, {
    "id": 2,
    "first_name": "Rania",
    "last_name": "Tungay",
    "email": "rtungay1@upenn.edu"
  }, {
    "id": 3,
    "first_name": "Miltie",
    "last_name": "MacAvddy",
    "email": "mmacavddy2@angelfire.com"
  }, {
    "id": 4,
    "first_name": "Edlin",
    "last_name": "Dalgety",
    "email": "edalgety3@eepurl.com"
  }, {
    "id": 5,
    "first_name": "Clayborn",
    "last_name": "Tootal",
    "email": "ctootal4@oaic.gov.au"
  }, {
    "id": 6,
    "first_name": "Pamela",
    "last_name": "Clemson",
    "email": "pclemson5@lulu.com"
  }, {
    "id": 7,
    "first_name": "Madonna",
    "last_name": "Laughren",
    "email": "mlaughren6@paginegialle.it"
  }, {
    "id": 8,
    "first_name": "Letta",
    "last_name": "Verryan",
    "email": "lverryan7@taobao.com"
  }, {
    "id": 9,
    "first_name": "Ernie",
    "last_name": "Wyrall",
    "email": "ewyrall8@meetup.com"
  }, {
    "id": 10,
    "first_name": "Traci",
    "last_name": "Arno",
    "email": "tarno9@yahoo.co.jp"
  }]
  module.exports=students;